name: Mon premier workflows


on: [push]


jobs:
  teste-job:
    run-on: unbuntu-latest
    steps:
      - name: Récupérer le code
        use: actions/checkout@v4


      - name: Dire bonjour
        run: echo"bonjour depuis Github actions !"


      - name: vérifier le fichier journal
        run: cat journal.txt
