name: Mon premier workflow

on: [push]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Dire bonjour
        run: echo "Bonjour depuis GitHub Actions !"

      - name: Vérifier le fichier journal
        run: cat journal.txt
