name: Mon premier workflow

on: [push]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Rendre le script exécutable
        run: chmod +x deploy.sh

      - name: Lancer le déploiement
        run: ./deploy.sh

      - name: Afficher le log de déploiement
        run: cat deploy.log
